### ISSUE TITLE
A screen transition denied me my potion flask!

### ISSUE THREAD

**Issue by DJChupa13** [silent-destroyer/tunic-randomizer-archipelago#2]
While I was going through a room transition, another AP player sent me my third potion flask shard.  However, when the transition was over, I didn't receive it.  The animation of the shard fusing together did not play, however the audio did.  Opening my inventory revealed I had 3/3 shards.

Receiving a fourth shard did not resolve the issue.  The menu now reads 4/3 shards lol.

When receiving my sixth shard, which would have netted me another potion, I did not receive it, rendering all subsequent shards useless.

Is there a way to stop the receipt of checks during a transition, and resume them when the transition is over?  Or, is there a way to reconcile the flask shard count?

**Comment by silent-destroyer** [comment]
Someone else reported this issue as well, so I will definitely be adding a failsafe to detect if you have more than 3 flask shards and automatically convert them into a full flask. For most items receiving them right before or during a transition usually doesn't cause an issue other than looking a bit jank, but there are a few edge cases like this that I will try and iron out for sure. It's a somewhat tricky thing to work around since it can't really be predicted that easily if the player is about to enter a load zone or not, but I will see what I can do to make it less jank overall.

**Comment by silent-destroyer** [comment]
This issue has been addressed in [version 0.0.3](https://github.com/silent-destroyer/tunic-randomizer-archipelago/releases/tag/0.0.3).
